### ISSUE TITLE
ExampleActivity error

### ISSUE THREAD

**Issue by igor961** [petterh/react-native-android-activity#7]
There is an error in ExampleActivity: it must be extended not by ReactActivity... With ReactActivity it does not work.

**Comment by sysfort** [comment]
* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/
4.1/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Java HotSpot(TM) Client VM warning: ignoring option MaxPermSize=512m; support wa
s removed in 8.0


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

**Comment by petterh** [comment]
1. @igor961  `ExampleActivity` works fine the way it is.
2. @sysfort It's not clear how your problems relate to this project.
